# Generated by Django 6.0.7 on 2026-07-29 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя Фамилия')),
                ('attendance', models.CharField(choices=[('alone', 'Да, я приду один (одна)'), ('couple', 'Да, я приду с супругой (-ом)'), ('decline', 'Нет, я не смогу прийти')], max_length=16, verbose_name='Ответ')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('wish', models.TextField(blank=True, verbose_name='Пожелание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'Ответ гостя',
                'verbose_name_plural': 'Ответы гостей',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(help_text='например 17:00', max_length=20, verbose_name='Время')),
                ('title', models.CharField(max_length=120, verbose_name='Событие')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Пункт программы',
                'verbose_name_plural': 'Программа вечера',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom', models.CharField(default='Айбек', max_length=60, verbose_name='Имя жениха')),
                ('bride', models.CharField(default='Арина', max_length=60, verbose_name='Имя невесты')),
                ('event_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='К этому времени идёт обратный отсчёт', verbose_name='Дата и время торжества')),
                ('quote', models.TextField(default='Наша любовь стала историей. Приглашаем вас быть её частью и разделить с нами мгновение, где начинается навсегда.', verbose_name='Цитата на конверте')),
                ('intro', models.TextField(default='Дорогие родные и друзья! С трепетом и радостью приглашаем вас разделить с нами самый важный день нашей жизни.', verbose_name='Текст приглашения')),
                ('venue_name', models.CharField(default='Elegant Emirates', max_length=120, verbose_name='Название заведения')),
                ('venue_address', models.CharField(default='г. Шымкент, пр. Байдибек би, 7/17', max_length=200, verbose_name='Адрес')),
                ('map_url', models.URLField(blank=True, default='https://2gis.kz/shymkent/search/Elegant%20Emirates', verbose_name='Ссылка на карту')),
                ('dress_code', models.CharField(default='Вечерний / Black tie', max_length=120, verbose_name='Дресс-код')),
                ('dress_code_note', models.CharField(blank=True, default='Будем признательны, если вы поддержите палитру торжества: оливковый, беж, шампань.', max_length=250, verbose_name='Пояснение к дресс-коду')),
                ('dress_colors', models.CharField(default='#4A5240,#6B7355,#8C9475,#C9BFA6,#EDE5D4', max_length=200, verbose_name='Цвета палитры (HEX через запятую)')),
                ('phone_1_label', models.CharField(blank=True, default='Айбек', max_length=60, verbose_name='Контакт 1 — имя')),
                ('phone_1', models.CharField(blank=True, default='+7 700 000 00 00', max_length=32, verbose_name='Контакт 1 — телефон')),
                ('phone_2_label', models.CharField(blank=True, default='Арина', max_length=60, verbose_name='Контакт 2 — имя')),
                ('phone_2', models.CharField(blank=True, default='+7 700 000 00 01', max_length=32, verbose_name='Контакт 2 — телефон')),
                ('rsvp_deadline', models.DateField(blank=True, null=True, verbose_name='Ответить до')),
                ('farewell', models.CharField(default='С любовью и трепетом ждём вас', max_length=200, verbose_name='Прощальная строка')),
                ('hero_image', models.ImageField(blank=True, upload_to='wedding/', verbose_name='Фото на обложку')),
                ('music', models.FileField(blank=True, upload_to='wedding/', verbose_name='Фоновая музыка (mp3)')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашение',
            },
        ),
    ]
