# Generated by Django 6.0.7 on 2026-07-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='event_title',
            field=models.CharField(default='Беташар тойға шақыру', help_text='Надпись над именами на обложке', max_length=120, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='bride',
            field=models.CharField(default='Дамира', max_length=60, verbose_name='Имя невесты'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='groom',
            field=models.CharField(default='Бексултан', max_length=60, verbose_name='Имя жениха'),
        ),
    ]
