# Generated by Django 6.0.7 on 2026-07-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_wedding_event_title_alter_wedding_bride_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wedding',
            name='quote',
        ),
        migrations.AlterField(
            model_name='wedding',
            name='intro',
            field=models.TextField(default='Дорогие родные и друзья! С трепетом и радостью приглашаем вас разделить с нами самый важный день нашей жизни.', verbose_name='Текст приглашения (в конверте)'),
        ),
    ]
