# Generated by Django 6.0.7 on 2026-07-29 09:00

import invitation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_remove_wedding_quote_alter_wedding_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='event_datetime',
            field=models.DateTimeField(default=invitation.models.default_event_datetime, help_text='К этому времени идёт обратный отсчёт', verbose_name='Дата и время торжества'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='intro',
            field=models.TextField(default='Дорогие родные и друзья! С трепетом и радостью приглашаем вас на наш беташар — разделите с нами этот особенный день.', verbose_name='Текст приглашения (в конверте)'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='map_url',
            field=models.URLField(blank=True, default='https://2gis.kz/astana/geo/70000001018072481/71.421419,51.134270', verbose_name='Ссылка на карту'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='phone_1',
            field=models.CharField(blank=True, max_length=32, verbose_name='Контакт 1 — телефон'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='phone_1_label',
            field=models.CharField(blank=True, default='Бексултан', max_length=60, verbose_name='Контакт 1 — имя'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='phone_2',
            field=models.CharField(blank=True, max_length=32, verbose_name='Контакт 2 — телефон'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='phone_2_label',
            field=models.CharField(blank=True, default='Дамира', max_length=60, verbose_name='Контакт 2 — имя'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='rsvp_deadline',
            field=models.DateField(blank=True, default=invitation.models.default_rsvp_deadline, null=True, verbose_name='Ответить до'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='venue_address',
            field=models.CharField(default='г. Астана, летняя площадка', max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='venue_name',
            field=models.CharField(default='Rixos President Astana', max_length=120, verbose_name='Название заведения'),
        ),
    ]
